# -*- coding: utf-8 -*-
"""SS_Prototype

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIunOnU6QwNPp_FOed2G9bZGzgcaiDt3
"""

"""
Smart Swachh - Citizen Waste Reporting Portal
Enhanced version with OpenAI image classification
"""
pip install -r requirements.txt

import streamlit as st
import pandas as pd
from datetime import datetime, date, time
import os
import re
import base64
from openai import OpenAI

# Configuration
CSV_FILE = "smart_swachh_reports.csv"

# Initialize session state
if 'form_submitted' not in st.session_state:
    st.session_state.form_submitted = False
if 'classified_category' not in st.session_state:
    st.session_state.classified_category = None
if 'classified_subcategory' not in st.session_state:
    st.session_state.classified_subcategory = None

# Category mappings
CATEGORIES = {
    "Cars": [],
    "Bikes": ["Motorcycles", "Scooters", "Spare Parts", "Bicycles"],
    "Electronics & Appliances": ["TVs, Video - Audio", "Kitchen & Other Appliances",
                                  "Computers & Laptops", "Cameras & Lenses"],
    "Mobiles": ["Mobile Phones", "Accessories", "Tablets"],
    "Commercial Vehicles & Spares": ["Commercial & Other Vehicles", "Spare Parts"],
    "Furniture": ["Sofa & Dining", "Beds & Wardrobes", "Home Decor & Garden",
                  "Kids Furniture", "Other Household Items"],
    "Fashion": ["Men", "Women", "Kids"],
    "Books, Sports & Hobbies": ["Books", "Gym & Fitness", "Musical Instruments",
                                 "Sports Equipment", "Other Hobbies"]}

def validate_phone(phone):
    """Validate Indian phone number format"""
    pattern = r'^[6-9]\d{9}$'
    return bool(re.match(pattern, phone))

def validate_email(email):
    """Validate email format"""
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return bool(re.match(pattern, email))

def validate_coordinates(lat, lon):
    """Validate latitude and longitude"""
    try:
        if lat and lon:
            lat_f = float(lat)
            lon_f = float(lon)
            return (-90 <= lat_f <= 90) and (-180 <= lon_f <= 180)
        return True
    except ValueError:
        return False

def encode_image_to_base64(image_file):
    """Convert uploaded image to base64"""
    return base64.b64encode(image_file.read()).decode('utf-8')

def classify_image_with_openai(image_file, api_key):
    """Classify image using OpenAI Vision API"""
    try:
        # Reset file pointer
        image_file.seek(0)

        # Encode image
        base64_image = encode_image_to_base64(image_file)
        image_file.seek(0)  # Reset again for later use

        # Initialize OpenAI client
        client = OpenAI(api_key=api_key)

        # Create category list for prompt
        category_list = "\n".join([f"- {cat}: {', '.join(subs) if subs else 'No subcategories'}"
                                   for cat, subs in CATEGORIES.items()])

        # Create prompt
        prompt = f"""Analyze this image and classify it into ONE of the following categories and its appropriate subcategory.

Available Categories and Subcategories:
{category_list}

Instructions:
1. Carefully examine the image
2. Identify what item/object is shown in the image
3. Match it to the MOST APPROPRIATE category and subcategory from the list above
4. Return ONLY a JSON object in this exact format (no additional text):
{{"category": "Category Name", "subcategory": "Subcategory Name"}}

If the subcategory list is empty or you cannot determine a specific subcategory, use "General" as the subcategory.
If the image doesn't match any category well, use the closest match.

Be precise and return only the JSON."""

        # Call OpenAI API
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{base64_image}"
                            }
                        }
                    ]
                }
            ],
            max_tokens=300
        )

        # Parse response
        result_text = response.choices[0].message.content.strip()

        # Remove markdown code blocks if present
        if result_text.startswith("```"):
            result_text = result_text.split("```")[1]
            if result_text.startswith("json"):
                result_text = result_text[4:]
        result_text = result_text.strip()

        # Parse JSON
        import json
        classification = json.loads(result_text)

        return classification.get("category"), classification.get("subcategory"), None

    except Exception as e:
        return None, None, str(e)

def save_report(report):
    """Save report to CSV safely with error handling"""
    try:
        df = pd.DataFrame([report])
        if os.path.exists(CSV_FILE):
            df_existing = pd.read_csv(CSV_FILE)
            df = pd.concat([df_existing, df], ignore_index=True)
        df.to_csv(CSV_FILE, index=False)
        return True
    except Exception as e:
        st.error(f"Error saving report: {str(e)}")
        return False

def save_uploaded_file(uploaded_file):
    """Save uploaded file to local directory"""
    try:
        if uploaded_file:
            if not os.path.exists("uploads"):
                os.makedirs("uploads")

            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{timestamp}_{uploaded_file.name}"
            filepath = os.path.join("uploads", filename)

            with open(filepath, "wb") as f:
                f.write(uploaded_file.getbuffer())

            return filename
    except Exception as e:
        st.error(f"Error saving file: {str(e)}")
        return None

# Page configuration
st.set_page_config(
    page_title="Smart Swachh Portal",
    page_icon="♻️",
    layout="wide"
)

# Sidebar for API Key
with st.sidebar:
    st.header("⚙️ Configuration")
    api_key = st.text_input("OpenAI API Key", type="password", help="Enter your OpenAI API key for image classification")
    st.markdown("---")
    st.markdown("### 📊 About Classification")
    st.info("Upload an image and the AI will automatically classify it into the appropriate category and subcategory.")
    st.markdown("---")
    st.markdown("### 🔒 Privacy")
    st.caption("Your API key is not stored and images are processed securely.")

# Header
st.title("♻️ Smart Swachh – Citizen Waste Reporting Portal")
st.markdown("### 🧾 Submit Waste Collection Request")
st.markdown("---")

# Create form
with st.form(key="waste_report_form", clear_on_submit=True):

    # Section 1: Personal Details
    st.header("👤 Personal Details")
    col1, col2 = st.columns(2)

    with col1:
        name = st.text_input("Full Name *", placeholder="Enter your full name")
        phone = st.text_input("Phone Number *", placeholder="10-digit mobile number")

    with col2:
        email = st.text_input("Email ID *", placeholder="your.email@example.com")

    st.markdown("---")

    # Section 2: Location Details
    st.header("📍 Location Details")

    col3, col4 = st.columns(2)
    with col3:
        lat = st.text_input("Latitude (optional)", placeholder="e.g., 12.9716")
    with col4:
        lon = st.text_input("Longitude (optional)", placeholder="e.g., 77.5946")

    address = st.text_area("Full Address *", placeholder="Enter complete address with area, city, and pincode", height=100)
    landmark = st.text_input("Landmark (optional)", placeholder="e.g., Near Bus Stop, Opposite Park")

    st.markdown("---")

    # Section 3: Upload Image (moved up)
    st.header("📸 Upload Image for Auto-Classification")
    uploaded_photo = st.file_uploader(
        "Upload an image of the item *",
        type=["jpg", "jpeg", "png"],
        help="Upload a clear image for automatic classification"
    )

    if uploaded_photo:
        col_img1, col_img2 = st.columns([1, 2])
        with col_img1:
            st.image(uploaded_photo, caption="Uploaded Image", use_container_width=True)

        with col_img2:
            if api_key:
                if st.form_submit_button("🤖 Classify Image with AI", type="secondary"):
                    with st.spinner("Analyzing image..."):
                        category, subcategory, error = classify_image_with_openai(uploaded_photo, api_key)

                        if error:
                            st.error(f"Classification error: {error}")
                        else:
                            st.session_state.classified_category = category
                            st.session_state.classified_subcategory = subcategory
                            st.success(f"✅ Classified as: **{category}** → **{subcategory}**")
            else:
                st.warning("⚠️ Please enter your OpenAI API key in the sidebar to enable auto-classification")

    st.markdown("---")

    # Section 4: Waste Details
    st.header("🗑️ Item Details")

    # Show classification results if available
    if st.session_state.classified_category:
        st.success(f"🤖 AI Classification: **{st.session_state.classified_category}** → **{st.session_state.classified_subcategory}**")

    col5, col6 = st.columns(2)

    with col5:
        # Use classified category as default if available
        category_list = ["Select Category"] + list(CATEGORIES.keys())
        default_category_idx = 0
        if st.session_state.classified_category and st.session_state.classified_category in CATEGORIES:
            default_category_idx = category_list.index(st.session_state.classified_category)

        category = st.selectbox(
            "Category *",
            category_list,
            index=default_category_idx,
            help="Select the category (auto-filled from AI classification)"
        )

        # Get subcategories
        if category != "Select Category":
            subcategories = CATEGORIES.get(category, [])
            if not subcategories:
                subcategory = "General"
                st.info("This category has no subcategories. Using 'General'.")
            else:
                # Use classified subcategory as default if available
                default_subcat_idx = 0
                if (st.session_state.classified_subcategory and
                    st.session_state.classified_subcategory in subcategories):
                    default_subcat_idx = subcategories.index(st.session_state.classified_subcategory)

                subcategory = st.selectbox(
                    "Subcategory *",
                    subcategories,
                    index=default_subcat_idx,
                    help="Select the subcategory (auto-filled from AI classification)"
                )
        else:
            subcategory = st.selectbox("Subcategory *", ["Select category first"])

    with col6:
        volume = st.slider("Approx. Volume (in liters) *", 1, 500, 10, help="Estimate the total volume")
        weight = st.slider("Approx. Weight (in kg) *", 1, 200, 5, help="Estimate the total weight")

    st.markdown("---")

    # Section 5: Collection Window
    st.header("🕒 Collection Window")

    col7, col8 = st.columns(2)

    with col7:
        collection_date = st.date_input(
            "Preferred Collection Date *",
            min_value=date.today(),
            help="Select a date from today onwards"
        )

    with col8:
        collection_time = st.time_input(
            "Preferred Collection Time *",
            value=time(9, 0),
            help="Select preferred collection time"
        )

    st.markdown("---")

    # Additional Notes
    st.header("📝 Additional Notes")
    notes = st.text_area(
        "Any special instructions or comments? (optional)",
        placeholder="e.g., Gate code, specific location details, handling instructions",
        height=80
    )

    # Submit button
    st.markdown("---")
    col_submit, col_empty = st.columns([1, 3])

    with col_submit:
        submit_button = st.form_submit_button("📤 Submit Report", use_container_width=True)

# Handle form submission
if submit_button:
    # Validation
    errors = []

    if not name or not name.strip():
        errors.append("❌ Full Name is required")

    if not phone:
        errors.append("❌ Phone Number is required")
    elif not validate_phone(phone):
        errors.append("❌ Please enter a valid 10-digit Indian mobile number")

    if not email:
        errors.append("❌ Email ID is required")
    elif not validate_email(email):
        errors.append("❌ Please enter a valid email address")

    if not address or not address.strip():
        errors.append("❌ Full Address is required")

    if not uploaded_photo:
        errors.append("❌ Please upload an image of the item")

    if category == "Select Category":
        errors.append("❌ Please select a Category (or use AI classification)")

    if (lat or lon) and not validate_coordinates(lat, lon):
        errors.append("❌ Invalid coordinates. Latitude must be between -90 and 90, Longitude between -180 and 180")

    # Display errors or submit
    if errors:
        st.error("### ⚠️ Please fix the following errors:")
        for error in errors:
            st.error(error)
    else:
        # Save uploaded file
        photo_filename = None
        if uploaded_photo:
            photo_filename = save_uploaded_file(uploaded_photo)

        # Create report dictionary
        report = {
            "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "Name": name.strip(),
            "Phone": phone,
            "Email": email.strip(),
            "Latitude": lat if lat else "N/A",
            "Longitude": lon if lon else "N/A",
            "Address": address.strip(),
            "Landmark": landmark.strip() if landmark else "N/A",
            "Category": category,
            "Subcategory": subcategory,
            "AI_Classified": "Yes" if st.session_state.classified_category else "No",
            "Volume(L)": volume,
            "Weight(Kg)": weight,
            "Collection_Date": collection_date.strftime("%Y-%m-%d"),
            "Collection_Time": collection_time.strftime("%H:%M"),
            "Photo": photo_filename if photo_filename else "No photo uploaded",
            "Notes": notes.strip() if notes else "N/A"
        }

        # Save report
        if save_report(report):
            st.success("### ✅ Your report has been submitted successfully!")
            st.balloons()

            # Display summary
            st.markdown("### 📋 Submission Summary")

            col_summary1, col_summary2 = st.columns(2)

            with col_summary1:
                st.markdown("**Personal Details:**")
                st.write(f"👤 Name: {report['Name']}")
                st.write(f"📱 Phone: {report['Phone']}")
                st.write(f"📧 Email: {report['Email']}")

                st.markdown("**Location:**")
                st.write(f"📍 Address: {report['Address']}")
                if report['Landmark'] != "N/A":
                    st.write(f"🚩 Landmark: {report['Landmark']}")

            with col_summary2:
                st.markdown("**Item Details:**")
                st.write(f"🗑️ Category: {report['Category']}")
                st.write(f"📦 Type: {report['Subcategory']}")
                if report['AI_Classified'] == "Yes":
                    st.write("🤖 AI Classified: Yes")
                st.write(f"📏 Volume: {report['Volume(L)']} liters")
                st.write(f"⚖️ Weight: {report['Weight(Kg)']} kg")

                st.markdown("**Collection Schedule:**")
                st.write(f"📅 Date: {report['Collection_Date']}")
                st.write(f"🕐 Time: {report['Collection_Time']}")

            st.info("📧 You will receive a confirmation email shortly with your request ID. Our team will contact you for collection scheduling.")

            # Reset classification state
            st.session_state.classified_category = None
            st.session_state.classified_subcategory = None
            st.session_state.form_submitted = True

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center; color: #666; padding: 20px;'>
        <p>♻️ Smart Swachh Initiative | Making cities cleaner, one report at a time</p>
        <p>For queries, contact: support@smartswachh.gov.in | Helpline: 1800-XXX-XXXX</p>
    </div>
    """,
    unsafe_allow_html=True
)
