# -*- coding: utf-8 -*-
"""SS_Prototype

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIunOnU6QwNPp_FOed2G9bZGzgcaiDt3
"""


import streamlit as st
from PIL import Image, ImageOps
import numpy as np
import pandas as pd
import os
import io
import time
from datetime import datetime

# -------------------------
# Config
# -------------------------
UPLOAD_DIR = "uploaded_images"
REPORT_CSV = "uploaded_images/reports.csv"
THUMB_SIZE = (224, 224)  # small thumbnail for storage/display

# Ensure directories exist
os.makedirs(UPLOAD_DIR, exist_ok=True)

# Initialize session state
if "reports_df" not in st.session_state:
    if os.path.exists(REPORT_CSV):
        try:
            st.session_state.reports_df = pd.read_csv(REPORT_CSV)
        except Exception:
            st.session_state.reports_df = pd.DataFrame(columns=[
                "id", "timestamp", "name", "lat", "lon", "category", "confidence",
                "image_path", "notes"
            ])
    else:
        st.session_state.reports_df = pd.DataFrame(columns=[
            "id", "timestamp", "name", "lat", "lon", "category", "confidence",
            "image_path", "notes"
        ])

# -------------------------
# Simple on-device classifier (heuristic)
# -------------------------
def classify_waste_pil(img_pil):
    """
    Very lightweight heuristic classifier:
    - Resizes and converts to numpy array
    - Computes mean of R,G,B channels
    - If green channel strongly dominant -> 'Wet / Organic'
    - Else -> 'Dry / Other'
    Returns (label, confidence_float)
    """
    try:
        img = img_pil.resize((64, 64)).convert("RGB")
        arr = np.asarray(img).astype(float) / 255.0  # shape (H,W,3)
        # mean channel values
        mean_r = arr[:, :, 0].mean()
        mean_g = arr[:, :, 1].mean()
        mean_b = arr[:, :, 2].mean()
        # compute simple score
        green_advantage = mean_g - max(mean_r, mean_b)
        # thresholds tuned for demo; confidence scaled to [0.5, 0.99]
        if green_advantage > 0.05:
            label = "Wet / Organic"
            confidence = min(0.99, 0.6 + green_advantage * 2.0)
        else:
            label = "Dry / Other"
            confidence = min(0.99, 0.55 + (-green_advantage) * 1.5)
        return label, float(confidence)
    except Exception:
        return "Unknown", 0.0

# -------------------------
# Helpers
# -------------------------
def save_thumbnail(img_pil, fname):
    thumb = ImageOps.exif_transpose(img_pil)
    thumb = thumb.convert("RGB")
    thumb.thumbnail(THUMB_SIZE)
    path = os.path.join(UPLOAD_DIR, fname)
    thumb.save(path, format="JPEG", quality=70)
    return path

def append_report_to_csv(report):
    df = st.session_state.reports_df
    df = df.append(report, ignore_index=True)
    st.session_state.reports_df = df
    try:
        df.to_csv(REPORT_CSV, index=False)
    except Exception as e:
        st.warning(f"Could not persist CSV: {e}")

def get_mock_co2_saved(num_reports):
    """
    Very simple mock estimate:
    Assume each optimized/clustered pickup avoids 0.05 kg CO2 (demo number)
    Multiply by number of reports for a conservative demo metric.
    NOTE: replace with realistic calculation in pilots.
    """
    return num_reports * 0.05  # kg CO2

# -------------------------
# UI Layout
# -------------------------
st.set_page_config(page_title="Smart Swachh (GreenMind Demo)", layout="wide")
st.title("Smart Swachh — Green AI Waste Reporting (Prototype)")

col1, col2 = st.columns([1, 1])

with col1:
    st.header("Report an Issue")
    st.markdown(
        "Upload a photo of the waste / overflowing bin. Provide coordinates (lat, lon). "
        "If you don't know coordinates, provide an approximate address or landmark."
    )
    name = st.text_input("Your name (optional)")
    uploaded_file = st.file_uploader("Upload image (jpg, png)", type=["jpg", "jpeg", "png"])
    lat = st.text_input("Latitude (decimal)", placeholder="e.g., 28.6139")
    lon = st.text_input("Longitude (decimal)", placeholder="e.g., 77.2090")
    notes = st.text_area("Notes (optional)")
    submit_btn = st.button("Submit Report")

    if submit_btn:
        if uploaded_file is None:
            st.error("Please upload an image to submit a report.")
        else:
            # load image
            try:
                img = Image.open(uploaded_file)
            except Exception as e:
                st.error(f"Unable to read uploaded image: {e}")
                img = None

            # classify (on-device heuristic)
            if img is not None:
                label, confidence = classify_waste_pil(img)
                # build safe filename
                ts = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
                fname = f"report_{ts}_{int(time.time() % 10000)}.jpg"
                saved_path = save_thumbnail(img, fname)

                # parse lat lon
                try:
                    lat_f = float(lat) if lat.strip() != "" else None
                    lon_f = float(lon) if lon.strip() != "" else None
                except Exception:
                    lat_f = None
                    lon_f = None

                # create report entry
                report = {
                    "id": f"R{int(time.time())}",
                    "timestamp": datetime.utcnow().isoformat(),
                    "name": name,
                    "lat": lat_f,
                    "lon": lon_f,
                    "category": label,
                    "confidence": round(confidence, 3),
                    "image_path": saved_path,
                    "notes": notes,
                }
                append_report_to_csv(report)

                st.success("Report submitted ✅")
                st.markdown(f"**Predicted category:** {label} (confidence: {confidence:.2f})")
                st.image(saved_path, width=300)
                if lat_f is None or lon_f is None:
                    st.info("You did not provide coordinates. You can edit the report CSV to add coordinates for mapping later.")
                else:
                    st.info("Report saved with coordinates — visible on the dashboard.")

with col2:
    st.header("Dashboard")
    st.markdown("Summary of submitted reports (local demo data).")

    df = st.session_state.reports_df.copy()
    if df.empty:
        st.info("No reports yet. Submit a report from the left panel to see demo data.")
    else:
        # clean df for display
        display_df = df[["timestamp", "name", "lat", "lon", "category", "confidence", "notes"]].copy()
        st.dataframe(display_df.sort_values(by="timestamp", ascending=False).reset_index(drop=True))

        st.markdown("**Map of reports (requires lat & lon in decimal).**")
        # st.map expects columns named 'lat' and 'lon' as floats and non-null
        map_df = df.dropna(subset=["lat", "lon"])
        if not map_df.empty:
            map_plot = map_df[["lat", "lon"]].rename(columns={"lat": "lat", "lon": "lon"})
            st.map(map_plot)
        else:
            st.info("No geotagged reports to map. Add lat/lon when submitting to visualize.")

        # simple stats
        total = len(df)
        wet = (df["category"] == "Wet / Organic").sum()
        dry = (df["category"] == "Dry / Other").sum()
        unknown = (df["category"] == "Unknown").sum()
        st.markdown("**Quick stats**")
        st.write(f"Total reports: {total}")
        st.write(f"Wet / Organic: {wet}")
        st.write(f"Dry / Other: {dry}")
        st.write(f"Unknown / Unable: {unknown}")

        co2_saved = get_mock_co2_saved(total)
        st.markdown(f"**Demo CO₂ saved (mock estimate):** {co2_saved:.3f} kg (very conservative demo value)")

# -------------------------
# Admin / Utilities
# -------------------------
st.markdown("---")
st.write("### Admin / Utilities")
colA, colB = st.columns([1, 1])
with colA:
    if st.button("Download reports CSV"):
        try:
            tmp = st.session_state.reports_df.to_csv(index=False).encode("utf-8")
            st.download_button("Click to download CSV", data=tmp, file_name="smart_swachh_reports.csv", mime="text/csv")
        except Exception as e:
            st.error(f"Could not create CSV download: {e}")

with colB:
    if st.button("Clear all reports (demo only)"):
        st.session_state.reports_df = st.session_state.reports_df.iloc[0:0]
        try:
            st.session_state.reports_df.to_csv(REPORT_CSV, index=False)
        except Exception:
            pass
        st.success("Cleared demo reports.")

st.markdown(
    """
    ---
    **Notes:**
    - This prototype uses a simple color-channel heuristic as a placeholder for an on-device model. Replace `classify_waste_pil()` with a TinyML TFLite model when available.
    - The CO₂ savings shown are mock conservative estimates for demo. Replace with measured route optimization numbers in pilots.
    - The prototype avoids any heavy cloud inference and stores only thumbnails + metadata by default to reduce data transfer and protect privacy.
    """
)
