# -*- coding: utf-8 -*-
"""SS_Prototype

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIunOnU6QwNPp_FOed2G9bZGzgcaiDt3
"""


import streamlit as st
import pandas as pd
from datetime import datetime
import geocoder
import os

# CSV path
CSV_FILE = "smart_swachh_reports.csv"

# Function to get geolocation
def get_location():
    g = geocoder.ip('me')
    if g.ok:
        return g.latlng
    else:
        return [None, None]

# Function to save report
def save_report(report):
    df = pd.DataFrame([report])
    if os.path.exists(CSV_FILE):
        df_existing = pd.read_csv(CSV_FILE)
        df = pd.concat([df_existing, df], ignore_index=True)
    df.to_csv(CSV_FILE, index=False)

# Streamlit app
st.title("♻️ Smart Swachh – Citizen Waste Reporting Portal")

st.markdown("### 🧾 Submit Waste Collection Request")

# Section 1: User Info
st.header("👤 Personal Details")
name = st.text_input("Full Name")
phone = st.text_input("Phone Number")
email = st.text_input("Email ID")

# Section 2: Location Details
st.header("📍 Location Details")
if st.button("Get Current Location (Auto-detect)"):
    lat, lon = get_location()
    st.session_state['lat'] = lat
    st.session_state['lon'] = lon
    st.success(f"Detected Location: Latitude {lat}, Longitude {lon}")

address = st.text_area("Full Address")
landmark = st.text_input("Landmark (optional)")

# Section 3: Waste Details
st.header("🗑️ Waste Details")
category = st.selectbox("Category", ["Household", "Commercial", "Event-based", "Industrial"])
subcategory = st.text_input("Subcategory (e.g., Plastic, Food, E-waste, etc.)")
volume = st.slider("Approx. Volume (in liters)", 1, 500, 10)
weight = st.slider("Approx. Weight (in kg)", 1, 200, 5)

# Section 4: Collection Schedule
st.header("🕒 Collection Window")
collection_date = st.date_input("Preferred Collection Date")
collection_time = st.time_input("Preferred Collection Time")

# Section 5: Upload Image
st.header("📸 Upload Image")
uploaded_photo = st.file_uploader("Upload an image of the waste", type=["jpg", "jpeg", "png"])

# Submit
if st.button("📤 Submit Report"):
    report = {
        "Timestamp": datetime.now(),
        "Name": name,
        "Phone": phone,
        "Email": email,
        "Latitude": st.session_state.get('lat'),
        "Longitude": st.session_state.get('lon'),
        "Address": address,
        "Landmark": landmark,
        "Category": category,
        "Subcategory": subcategory,
        "Volume(L)": volume,
        "Weight(Kg)": weight,
        "Collection_Date": collection_date,
        "Collection_Time": collection_time,
        "Photo": uploaded_photo.name if uploaded_photo else None
    }

    save_report(report)
    st.success("✅ Your report has been submitted successfully!")

    st.write("### 📋 Summary of Submission:")
    st.json(report)
